# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/yaroslav/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/201.7223.86/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Users/yaroslav/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/201.7223.86/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yaroslav/Developer/Study/POOP/Paint

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yaroslav/Developer/Study/POOP/Paint

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/yaroslav/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/201.7223.86/CLion.app/Contents/bin/cmake/mac/bin/cmake" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/yaroslav/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/201.7223.86/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yaroslav/Developer/Study/POOP/Paint/CMakeFiles /Users/yaroslav/Developer/Study/POOP/Paint/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yaroslav/Developer/Study/POOP/Paint/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Paint

# Build rule for target.
Paint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Paint
.PHONY : Paint

# fast build rule for target.
Paint/fast:
	$(MAKE) -f CMakeFiles/Paint.dir/build.make CMakeFiles/Paint.dir/build
.PHONY : Paint/fast

#=============================================================================
# Target rules for targets named Paint_autogen

# Build rule for target.
Paint_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Paint_autogen
.PHONY : Paint_autogen

# fast build rule for target.
Paint_autogen/fast:
	$(MAKE) -f CMakeFiles/Paint_autogen.dir/build.make CMakeFiles/Paint_autogen.dir/build
.PHONY : Paint_autogen/fast

Paint_autogen/mocs_compilation.o: Paint_autogen/mocs_compilation.cpp.o

.PHONY : Paint_autogen/mocs_compilation.o

# target to build an object file
Paint_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/Paint.dir/build.make CMakeFiles/Paint.dir/Paint_autogen/mocs_compilation.cpp.o
.PHONY : Paint_autogen/mocs_compilation.cpp.o

Paint_autogen/mocs_compilation.i: Paint_autogen/mocs_compilation.cpp.i

.PHONY : Paint_autogen/mocs_compilation.i

# target to preprocess a source file
Paint_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/Paint.dir/build.make CMakeFiles/Paint.dir/Paint_autogen/mocs_compilation.cpp.i
.PHONY : Paint_autogen/mocs_compilation.cpp.i

Paint_autogen/mocs_compilation.s: Paint_autogen/mocs_compilation.cpp.s

.PHONY : Paint_autogen/mocs_compilation.s

# target to generate assembly for a file
Paint_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/Paint.dir/build.make CMakeFiles/Paint.dir/Paint_autogen/mocs_compilation.cpp.s
.PHONY : Paint_autogen/mocs_compilation.cpp.s

src/PaintWindow/PaintWindow.o: src/PaintWindow/PaintWindow.cpp.o

.PHONY : src/PaintWindow/PaintWindow.o

# target to build an object file
src/PaintWindow/PaintWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Paint.dir/build.make CMakeFiles/Paint.dir/src/PaintWindow/PaintWindow.cpp.o
.PHONY : src/PaintWindow/PaintWindow.cpp.o

src/PaintWindow/PaintWindow.i: src/PaintWindow/PaintWindow.cpp.i

.PHONY : src/PaintWindow/PaintWindow.i

# target to preprocess a source file
src/PaintWindow/PaintWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Paint.dir/build.make CMakeFiles/Paint.dir/src/PaintWindow/PaintWindow.cpp.i
.PHONY : src/PaintWindow/PaintWindow.cpp.i

src/PaintWindow/PaintWindow.s: src/PaintWindow/PaintWindow.cpp.s

.PHONY : src/PaintWindow/PaintWindow.s

# target to generate assembly for a file
src/PaintWindow/PaintWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Paint.dir/build.make CMakeFiles/Paint.dir/src/PaintWindow/PaintWindow.cpp.s
.PHONY : src/PaintWindow/PaintWindow.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Paint.dir/build.make CMakeFiles/Paint.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Paint.dir/build.make CMakeFiles/Paint.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Paint.dir/build.make CMakeFiles/Paint.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Paint"
	@echo "... Paint_autogen"
	@echo "... Paint_autogen/mocs_compilation.o"
	@echo "... Paint_autogen/mocs_compilation.i"
	@echo "... Paint_autogen/mocs_compilation.s"
	@echo "... src/PaintWindow/PaintWindow.o"
	@echo "... src/PaintWindow/PaintWindow.i"
	@echo "... src/PaintWindow/PaintWindow.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

